In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



%matplotlib inline

In [10]:
test_data = pd.read_csv('test.txt', delimiter=';', names=['comment','emotions'])
train_data = pd.read_csv('train.txt', delimiter=';', names =['comment','emotions'])
val_data = pd.read_csv('val.txt', delimiter=';', names =['comment','emotions'])

In [11]:
test_data

                                                comment emotions
0     im feeling rather rotten so im not very ambiti...  sadness
1             im updating my blog because i feel shitty  sadness
2     i never make her separate from me because i do...  sadness
3     i left with my bouquet of red and yellow tulip...      joy
4       i was feeling a little vain when i did this one  sadness
...                                                 ...      ...
1995  i just keep feeling like someone is being unki...    anger
1996  im feeling a little cranky negative after this...    anger
1997  i feel that i am useful to my people and that ...      joy
1998  im feeling more comfortable with derby i feel ...      joy
1999  i feel all weird when i have to meet w people ...     fear

[2000 rows x 2 columns]

In [12]:
train_data

                                                 comment emotions
0                                i didnt feel humiliated  sadness
1      i can go from feeling so hopeless to so damned...  sadness
2       im grabbing a minute to post i feel greedy wrong    anger
3      i am ever feeling nostalgic about the fireplac...     love
4                                   i am feeling grouchy    anger
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...  sadness
15996  i am now turning and i feel pathetic that i am...  sadness
15997                     i feel strong and good overall      joy
15998  i feel like this was such a rude comment and i...    anger
15999  i know a lot but i feel so stupid because i ca...  sadness

[16000 rows x 2 columns]

In [13]:
val_data

                                                comment emotions
0     im feeling quite sad and sorry for myself but ...  sadness
1     i feel like i am still looking at a blank canv...  sadness
2                        i feel like a faithful servant     love
3                     i am just feeling cranky and blue    anger
4     i can have for a treat or if i am feeling festive      joy
...                                                 ...      ...
1995  im having ssa examination tomorrow in the morn...  sadness
1996  i constantly worry about their fight against n...      joy
1997  i feel its important to share this info for th...      joy
1998  i truly feel that if you are passionate enough...      joy
1999  i feel like i just wanna buy any cute make up ...      joy

[2000 rows x 2 columns]

In [14]:
train_data['emotions'].nunique()

6

In [20]:
train_data['emotions'].value_counts()

emotions
joy         5362
sadness     4666
anger       2159
fear        1937
love        1304
surprise     572
Name: count, dtype: int64

In [31]:
test_data['emotions'].value_counts()

emotions
joy         695
sadness     581
anger       275
fear        224
love        159
surprise     66
Name: count, dtype: int64

In [21]:
train_data['target'] = train_data['emotions'].map({
    'joy': 1,'sadness':2, 'anger':3,'fear':4, 'love':5, 'surprise':6
})

In [30]:
test_data['target'] = test_data['emotions'].map({
    'joy': 1,'sadness':2, 'anger':3,'fear':4, 'love':5, 'surprise':6
})

In [22]:
train_data

                                                 comment emotions  target
0                                i didnt feel humiliated  sadness       2
1      i can go from feeling so hopeless to so damned...  sadness       2
2       im grabbing a minute to post i feel greedy wrong    anger       3
3      i am ever feeling nostalgic about the fireplac...     love       5
4                                   i am feeling grouchy    anger       3
...                                                  ...      ...     ...
15995  i just had a very brief time in the beanbag an...  sadness       2
15996  i am now turning and i feel pathetic that i am...  sadness       2
15997                     i feel strong and good overall      joy       1
15998  i feel like this was such a rude comment and i...    anger       3
15999  i know a lot but i feel so stupid because i ca...  sadness       2

[16000 rows x 3 columns]

In [27]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.naive_bayes import MultinomialNB

//Let us firstly use the random forest as it is good for classification.

In [32]:
rf_pipeline = Pipeline(
[
    ('vectorizer',CountVectorizer(ngram_range=(3,3))),
    ('rfc', RandomForestClassifier()),

]
)

model_rf = rf_pipeline.fit(train_data['comment'], train_data['target'])

y_pred_rf = model_rf.predict(test_data['comment'])

report_rf = classification_report(test_data['comment'], test_data['target'])

report_rf

In [ ]:
mnb_pipeline = Pipeline(
[
    ('vectorizer',CountVectorizer(ngram_range=(1,2))),
    ('mnb', MultinomialNB()),

]
)

model_mnb = rf_pipeline.fit(train_data['comment'], train_data['target'])

y_pred_mnb = model_rf.predict(test_data['comment'])

report_mnb = classification_report(test_data['comment'], test_data['target'])

report_mnb

In [ ]:

clf = Pipeline([
     ('vectorizer_tfidf',TfidfVectorizer()),        
     ('Random Forest', RandomForestClassifier())         
])


clf.fit(train_data['comment'], train_data['target'])


y_pred = clf.predict(test_data['comment'])



print(classification_report(test_data['comment'], test_data['target']))